# Generated by Django 3.1.5 on 2021-01-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostorfound',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='img_upload/'),
        ),
    ]
