# Generated by Django 3.1.5 on 2021-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostorfound',
            name='data_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
