# Generated by Django 3.1.5 on 2021-02-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lostorfound_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostorfound',
            name='pin_number',
            field=models.PositiveIntegerField(default=100011),
        ),
        migrations.AddField(
            model_name='lostorfound',
            name='select',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lostorfound',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
