# Generated by Django 3.1.5 on 2021-02-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_lostorfound_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostorfound',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
