# Generated by Django 3.1.5 on 2021-02-01 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20210201_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostorfound',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClaimOnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_on', models.ManyToManyField(blank=True, to='app1.LostOrFound')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
