# Generated by Django 3.1.5 on 2021-02-17 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210217_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostorfound',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
