# Generated by Django 3.1.5 on 2021-02-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210217_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostorfound',
            name='phone_number',
            field=models.PositiveIntegerField(default=999999999),
        ),
    ]
