# Generated by Django 3.1.5 on 2021-02-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210201_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostorfound',
            name='claimed',
        ),
        migrations.DeleteModel(
            name='ClaimOnProduct',
        ),
    ]
