# Generated by Django 3.1.5 on 2021-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210217_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostorfound',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
