# Generated by Django 3.1.5 on 2021-02-22 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
